kind: Deployment
apiVerison: extensions/v1beta;
metadata:
    name: ebl-deployment
    replicas: 1
    selector:
        matchLabels:
        app: ebl
    template:
        metadata:
            labels:
                app: ebl
        spec:
